
services:
  db:
    image: mariadb:11.2
    restart: always
    environment:
      MARIADB_DATABASE: fooddelivery
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mariadb://db:3306/fooddelivery
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_VALIDITY=${JWT_ACCESS_TOKEN_VALIDITY}
      - JWT_REFRESH_TOKEN_VALIDITY=${JWT_REFRESH_TOKEN_VALIDITY}
      - UPLOAD_FILE_BASE_URI=file:///app/upload/
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - APP_BASE_URL=${APP_BASE_URL}
    depends_on:
      - db
    volumes:
      - ./upload:/app/upload

volumes:
  db_data: